#!/usr/bin/env bash
# a bash script that pings an P address passed as an argument.
# Requirements:
# Accept a string as an argument
# Displays usage: 5-is_the_host_on_the_network {IP_ADDRESS}
# if no argument passed
# ping the IP 5 times

if [ $# -eq 0 ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit
elif [ $# -gt 1 ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit
else
	ping "$1" -c 5
fi

